# Generated by Django 5.2 on 2025-04-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_inventario_cantidad_alter_inventario_pieza'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='inventario',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
