# Generated by Django 5.2 on 2025-04-09 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_etiquetas_remove_inventario_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='orden_trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(max_length=50, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='etiquetas',
            name='zpl_template',
            field=models.TextField(default='', help_text='Código ZPL con placeholders como {{qr}}, {{pieza}}, etc.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventario',
            name='orden_trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piezas', to='polls.orden_trabajo'),
        ),
    ]
