# Generated by Django 5.2 on 2025-04-10 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_inventario_fecha_creacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='work_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='etiquetas',
            new_name='labels',
        ),
        migrations.RenameField(
            model_name='labels',
            old_name='nombre',
            new_name='name',
        ),
        migrations.CreateModel(
            name='equipment_labels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.CharField(max_length=18)),
                ('quantity', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('work_orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piezas', to='polls.work_orders')),
            ],
        ),
        migrations.DeleteModel(
            name='inventario',
        ),
        migrations.DeleteModel(
            name='orden_trabajo',
        ),
    ]
