# Generated by Django 5.2 on 2025-04-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_work_orders_rename_etiquetas_labels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_orders',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
