# Generated by Django 5.2 on 2025-04-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_work_orders_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_orders',
            name='work_cell',
            field=models.CharField(default='', max_length=50),
        ),
    ]
