# Generated by Django 5.2 on 2025-04-15 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_work_orders_work_cell'),
    ]

    operations = [
        migrations.CreateModel(
            name='work_cells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_cell', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='work_orders',
            name='work_cell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='polls.work_cells'),
        ),
    ]
