# Generated by Django 5.2 on 2025-04-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_work_cells_alter_work_orders_work_cell'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_cells',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='small', max_length=10),
        ),
    ]
