# Generated by Django 5.2.7 on 2025-10-09 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_work_cells_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work_orders',
            name='work_cell',
        ),
        migrations.AddField(
            model_name='work_orders',
            name='cell',
            field=models.CharField(default='', max_length=50),
        ),
    ]
