# Generated by Django 5.2.7 on 2025-10-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_remove_work_orders_work_cell_work_orders_cell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment_labels',
            name='work_orders',
        ),
        migrations.AddField(
            model_name='equipment_labels',
            name='label_type',
            field=models.CharField(choices=[('qr', 'QR Code'), ('barcode', 'Código de Barras')], default=0),
            preserve_default=False,
        ),
    ]
